import { auth } from "@/auth";
import { redirect } from "next/navigation";
import { db } from "@/lib/db";
import { can } from "@/lib/rbac";
import DocSettingsForm from "./DocSettingsForm";

export default async function DocSettingsPage() {
  const session = await auth();
  if (!session || !session.user) {
    redirect("/auth/signin");
  }

  const user = session.user as any;
  const isAllowed = can(user, "company.settings.edit") || can(user, "numbering.config");

  if (!isAllowed) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[400px] text-center font-body bg-white border border-onyx/5 rounded-xl p-8">
        <h2 className="text-lg font-bold text-red-700">Access Denied</h2>
        <p className="text-xs text-onyx/60 mt-2">
          You do not have administrative permissions to edit document settings or numbering schemes.
        </p>
      </div>
    );
  }

  // Fetch document settings
  let docSettings = await db.companyDocumentSettings.findUnique({
    where: { companyId: user.companyId },
  });

  if (!docSettings) {
    docSettings = await db.companyDocumentSettings.create({
      data: {
        companyId: user.companyId,
        poHeaderNote: "Thank you for your business. Please deliver items per terms.",
        poFooterNote: "Generated by Saarlekha Stores & Purchase System.",
        authorizedSignatory: "Stores & Purchase Officer",
        declaration: "We declare that this purchase order shows the actual price of the goods described and that all particulars are true and correct.",
      },
    });
  }

  // Fetch numbering schemes
  const numberingSchemes = await db.numberingScheme.findMany({
    where: { companyId: user.companyId },
  });

  return (
    <DocSettingsForm
      initialSettings={JSON.parse(JSON.stringify(docSettings))}
      initialSchemes={JSON.parse(JSON.stringify(numberingSchemes))}
      userPermissions={{
        docSettings: can(user, "company.settings.edit"),
        numbering: can(user, "numbering.config"),
      }}
    />
  );
}
